#!/bin/bash

REMOTE_IMAGE="timchinowsky/build_circuitpython"

LOCAL_IMAGE=$REMOTE_IMAGE

make fetch-all-submodules

docker pull $REMOTE_IMAGE

docker run --user $UID:$(id -g) -it -v .:/circuitpython $LOCAL_IMAGE /tools/build.sh "$@"
